// Mongoose model validation message constants for i18n support
// These constants are used in Mongoose schema validation messages

export const MODEL_VALIDATION_MESSAGES = {
  // Common Field Requirements
  FIELD_REQUIRED: 'FIELD_REQUIRED',

  // User Model Validation
  USER_NAME_REQUIRED: 'USER_NAME_REQUIRED',
  USER_EMAIL_REQUIRED: 'USER_EMAIL_REQUIRED',
  USER_PASSWORD_REQUIRED: 'USER_PASSWORD_REQUIRED',
  USER_ROLE_REQUIRED: 'USER_ROLE_REQUIRED',

  // User Field Length Validation
  USER_NAME_MAX_LENGTH: 'USER_NAME_MAX_LENGTH',
  USER_PASSWORD_MIN_LENGTH: 'USER_PASSWORD_MIN_LENGTH',
  USER_DEPARTMENT_MAX_LENGTH: 'USER_DEPARTMENT_MAX_LENGTH',
  USER_POSITION_MAX_LENGTH: 'USER_POSITION_MAX_LENGTH',
  USER_PHONE_MAX_LENGTH: 'USER_PHONE_MAX_LENGTH',
  USER_WEBSITE_MAX_LENGTH: 'USER_WEBSITE_MAX_LENGTH',

  // User Field Format Validation
  USER_EMAIL_INVALID_FORMAT: 'USER_EMAIL_INVALID_FORMAT',

  // Role Model Validation
  ROLE_NAME_REQUIRED: 'ROLE_NAME_REQUIRED',
  ROLE_DESCRIPTION_REQUIRED: 'ROLE_DESCRIPTION_REQUIRED',
  ROLE_NAME_MAX_LENGTH: 'ROLE_NAME_MAX_LENGTH',
  ROLE_DESCRIPTION_MAX_LENGTH: 'ROLE_DESCRIPTION_MAX_LENGTH',

  // Permission Model Validation
  PERMISSION_NAME_REQUIRED: 'PERMISSION_NAME_REQUIRED',
  PERMISSION_DESCRIPTION_REQUIRED: 'PERMISSION_DESCRIPTION_REQUIRED',
  PERMISSION_MODULE_REQUIRED: 'PERMISSION_MODULE_REQUIRED',
  PERMISSION_ACTION_REQUIRED: 'PERMISSION_ACTION_REQUIRED',
  PERMISSION_RESOURCE_REQUIRED: 'PERMISSION_RESOURCE_REQUIRED',
  PERMISSION_TYPE_REQUIRED: 'PERMISSION_TYPE_REQUIRED',

  // Permission Field Length Validation
  PERMISSION_NAME_MAX_LENGTH: 'PERMISSION_NAME_MAX_LENGTH',
  PERMISSION_DESCRIPTION_MAX_LENGTH: 'PERMISSION_DESCRIPTION_MAX_LENGTH',
  PERMISSION_MODULE_MAX_LENGTH: 'PERMISSION_MODULE_MAX_LENGTH',
  PERMISSION_RESOURCE_MAX_LENGTH: 'PERMISSION_RESOURCE_MAX_LENGTH',

  // Common Field Length Messages (with placeholders)
  MAX_LENGTH_100: 'MAX_LENGTH_100',
  MAX_LENGTH_200: 'MAX_LENGTH_200',
  MAX_LENGTH_50: 'MAX_LENGTH_50',
  MAX_LENGTH_20: 'MAX_LENGTH_20',
  MIN_LENGTH_6: 'MIN_LENGTH_6',

  // Email Format
  EMAIL_INVALID_FORMAT: 'EMAIL_INVALID_FORMAT'
} as const

// Type for validation message keys
export type ValidationMessageKey = typeof MODEL_VALIDATION_MESSAGES[keyof typeof MODEL_VALIDATION_MESSAGES]